/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogodavelha;
import java.awt.Color;
/**
 *
 * @author laboratorio
 */
public class JogoDaVelhaFrame extends javax.swing.JFrame {

    /**
     * Creates new form JogoDaVelhaFrame
     */
    public JogoDaVelhaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpainel1 = new javax.swing.JPanel();
        jbotao1 = new javax.swing.JButton();
        jbotao2 = new javax.swing.JButton();
        jbotao3 = new javax.swing.JButton();
        jbotao4 = new javax.swing.JButton();
        jbotao5 = new javax.swing.JButton();
        jbotao6 = new javax.swing.JButton();
        jbotao7 = new javax.swing.JButton();
        jbotao8 = new javax.swing.JButton();
        jbotao9 = new javax.swing.JButton();
        jIniciar = new javax.swing.JButton();
        jJogadorVez = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbotao1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbotao1.setForeground(new java.awt.Color(255, 255, 255));
        jbotao1.setEnabled(false);
        jbotao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotao1ActionPerformed(evt);
            }
        });

        jbotao2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbotao2.setEnabled(false);
        jbotao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotao2ActionPerformed(evt);
            }
        });

        jbotao3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbotao3.setEnabled(false);
        jbotao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotao3ActionPerformed(evt);
            }
        });

        jbotao4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbotao4.setEnabled(false);
        jbotao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotao4ActionPerformed(evt);
            }
        });

        jbotao5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbotao5.setEnabled(false);
        jbotao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotao5ActionPerformed(evt);
            }
        });

        jbotao6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbotao6.setEnabled(false);
        jbotao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotao6ActionPerformed(evt);
            }
        });

        jbotao7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbotao7.setEnabled(false);
        jbotao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotao7ActionPerformed(evt);
            }
        });

        jbotao8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbotao8.setEnabled(false);
        jbotao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotao8ActionPerformed(evt);
            }
        });

        jbotao9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbotao9.setEnabled(false);
        jbotao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotao9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpainel1Layout = new javax.swing.GroupLayout(jpainel1);
        jpainel1.setLayout(jpainel1Layout);
        jpainel1Layout.setHorizontalGroup(
            jpainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpainel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpainel1Layout.createSequentialGroup()
                        .addComponent(jbotao7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbotao8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbotao9))
                    .addGroup(jpainel1Layout.createSequentialGroup()
                        .addComponent(jbotao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbotao2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbotao3))
                    .addGroup(jpainel1Layout.createSequentialGroup()
                        .addComponent(jbotao4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbotao5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbotao6)))
                .addGap(8, 8, 8))
        );

        jpainel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbotao1, jbotao2, jbotao3, jbotao4, jbotao5, jbotao6, jbotao7, jbotao8, jbotao9});

        jpainel1Layout.setVerticalGroup(
            jpainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpainel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpainel1Layout.createSequentialGroup()
                        .addGroup(jpainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpainel1Layout.createSequentialGroup()
                                .addComponent(jbotao3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpainel1Layout.createSequentialGroup()
                                .addComponent(jbotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jpainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbotao6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbotao5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpainel1Layout.createSequentialGroup()
                        .addComponent(jbotao1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbotao4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbotao7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbotao8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbotao9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpainel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbotao1, jbotao2, jbotao3, jbotao4, jbotao5, jbotao6, jbotao7, jbotao8, jbotao9});

        jIniciar.setText("Iniciar");
        jIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIniciarActionPerformed(evt);
            }
        });

        jJogadorVez.setText("Precione Iniciar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jIniciar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jJogadorVez, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jJogadorVez)
                .addGap(2, 2, 2)
                .addComponent(jpainel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jIniciar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jbotao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotao1ActionPerformed
        if (JogadorAtual == 1) {
            jbotao1.setText("O");
            mat[0][0] = 1;
             apresentaMatriz();
            JogadorAtual = 2;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        } else {
            jbotao1.setText("X");
            mat[0][0] = 2;
            JogadorAtual = 1;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        }
        
        apresentaMatriz();
        verificaGanhador();
        jbotao1.setEnabled(false);
        jIniciar.setText("Reiniciar");
    }//GEN-LAST:event_jbotao1ActionPerformed

    private void jbotao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotao5ActionPerformed
        if (JogadorAtual == 1) {
            jbotao5.setText("O");
            mat[1][1] = 1;
             apresentaMatriz();
            JogadorAtual = 2;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        } else {
            jbotao5.setText("X");
            mat[1][1] = 2;
            JogadorAtual = 1;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        }
        
        apresentaMatriz();
        verificaGanhador();
        jbotao5.setEnabled(false);
        jIniciar.setText("Reiniciar");
    }//GEN-LAST:event_jbotao5ActionPerformed

    private void jbotao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotao6ActionPerformed
        if (JogadorAtual == 1) {
            jbotao6.setText("O");
            mat[1][2] = 1;
             apresentaMatriz();
            JogadorAtual = 2;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        } else {
            jbotao6.setText("X");
            mat[1][2] = 2;
            JogadorAtual = 1;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        }
        
        apresentaMatriz();
        verificaGanhador();
        jbotao6.setEnabled(false);
    }//GEN-LAST:event_jbotao6ActionPerformed

    private void jbotao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotao8ActionPerformed
        if (JogadorAtual == 1) {
            jbotao8.setText("O");
            mat[2][1] = 1;
             apresentaMatriz();
            JogadorAtual = 2;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        } else {
            jbotao8.setText("X");
            mat[2][1] = 2;
            JogadorAtual = 1;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        }
        
        apresentaMatriz();
        verificaGanhador();
        jbotao8.setEnabled(false);
        jIniciar.setText("Reiniciar");
    }//GEN-LAST:event_jbotao8ActionPerformed

    private void jIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIniciarActionPerformed
        int a,b;
        for(a=0;a<3;a++){
            for(b=0;b<3;b++){
                mat[a][b] = 0;
        }
        }
        JogadorAtual = 1;
        jJogadorVez.setText("Jogador " + JogadorAtual);
        jbotao1.setEnabled(true);
        jbotao2.setEnabled(true);
        jbotao3.setEnabled(true);
        jbotao6.setEnabled(true);
        jbotao5.setEnabled(true);
        jbotao4.setEnabled(true);
        jbotao7.setEnabled(true);
        jbotao8.setEnabled(true);
        jbotao9.setEnabled(true);
        
        jbotao1.setText("");
        jbotao2.setText("");
        jbotao3.setText("");
        jbotao4.setText("");
        jbotao5.setText("");
        jbotao6.setText("");
        jbotao7.setText("");
        jbotao8.setText("");
        jbotao9.setText("");
        jIniciar.setText("Iniciar");
    }//GEN-LAST:event_jIniciarActionPerformed

    private void jbotao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotao2ActionPerformed
         if (JogadorAtual == 1) {
            jbotao2.setText("O");
            mat[0][1] = 1;
             apresentaMatriz();
            JogadorAtual = 2;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        } else {
            jbotao2.setText("X");
            mat[0][1] = 2;
            JogadorAtual = 1;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        }
        
        apresentaMatriz();
        verificaGanhador();
        jbotao2.setEnabled(false);
        jIniciar.setText("Reiniciar");
    }//GEN-LAST:event_jbotao2ActionPerformed

    private void jbotao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotao3ActionPerformed
         if (JogadorAtual == 1) {
            jbotao3.setText("O");
            mat[0][2] = 1;
             apresentaMatriz();
            JogadorAtual = 2;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        } else {
            jbotao3.setText("X");
            mat[0][2] = 2;
            JogadorAtual = 1;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        }
        
        apresentaMatriz();
        verificaGanhador();
        jbotao3.setEnabled(false);
        jIniciar.setText("Reiniciar");
    }//GEN-LAST:event_jbotao3ActionPerformed

    private void jbotao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotao4ActionPerformed
        if (JogadorAtual == 1) {
            jbotao4.setText("O");
            mat[1][0] = 1;
             apresentaMatriz();
            JogadorAtual = 2;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        } else {
            jbotao4.setText("X");
            mat[1][0] = 2;
            JogadorAtual = 1;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        }
        
        apresentaMatriz();
        verificaGanhador();
        jbotao4.setEnabled(false);
        jIniciar.setText("Reiniciar");
    }//GEN-LAST:event_jbotao4ActionPerformed

    private void jbotao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotao7ActionPerformed
        if (JogadorAtual == 1) {
            jbotao7.setText("O");
            mat[2][0] = 1;
             apresentaMatriz();
            JogadorAtual = 2;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        } else {
            jbotao7.setText("X");
            mat[2][0] = 2;
            JogadorAtual = 1;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        }
        
        apresentaMatriz();
        verificaGanhador();
        jbotao7.setEnabled(false);
        jIniciar.setText("Reiniciar");
    }//GEN-LAST:event_jbotao7ActionPerformed

    private void jbotao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotao9ActionPerformed
        if (JogadorAtual == 1) {
            jbotao9.setText("O");
            mat[2][2] = 1;
             apresentaMatriz();
            JogadorAtual = 2;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        } else {
            jbotao9.setText("X");
            mat[2][2] = 2;
            JogadorAtual = 1;
            jJogadorVez.setText("Jogador " + JogadorAtual);
        }
        
        apresentaMatriz();
        verificaGanhador();
        jbotao9.setEnabled(false);
        jIniciar.setText("Reiniciar");
    }//GEN-LAST:event_jbotao9ActionPerformed
    int JogadorAtual = 0;
    int[][] mat = new int[3][3];
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoDaVelhaFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jIniciar;
    private javax.swing.JLabel jJogadorVez;
    private javax.swing.JButton jbotao1;
    private javax.swing.JButton jbotao2;
    private javax.swing.JButton jbotao3;
    private javax.swing.JButton jbotao4;
    private javax.swing.JButton jbotao5;
    private javax.swing.JButton jbotao6;
    private javax.swing.JButton jbotao7;
    private javax.swing.JButton jbotao8;
    private javax.swing.JButton jbotao9;
    private javax.swing.JPanel jpainel1;
    // End of variables declaration//GEN-END:variables

    private void apresentaMatriz() {
        int i,j;
        for(i=0;i<3;i++){
            for(j=0;j<3;j++){
                System.out.print(mat[i][j]+" ");
            }
            System.out.println(" ");
        }
        
    }

    private void verificaGanhador() {        
        int i,j;
        //Jogador 1 Vitorias
        
        //Coluna
        
        if(mat[0][0]==1&&mat[0][1]==1&&mat[0][2]==1){
            jJogadorVez.setText("Jogador 1 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        if(mat[1][0]==1&&mat[1][1]==1&&mat[1][2]==1){
            jJogadorVez.setText("Jogador 1 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        if(mat[2][0]==1&&mat[2][1]==1&&mat[2][2]==1){
            jJogadorVez.setText("Jogador 1 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        //Linha
        
        if(mat[0][0]==1&&mat[1][0]==1&&mat[2][0]==1){
            jJogadorVez.setText("Jogador 1 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        if(mat[0][1]==1&&mat[1][1]==1&&mat[2][1]==1){
            System.out.println("Jogador 1 venceu");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        if(mat[0][2]==1&&mat[1][2]==1&&mat[2][2]==1){
            jJogadorVez.setText("Jogador 1 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        //Diagonais
        
        if(mat[0][0]==1&&mat[1][1]==1&&mat[2][2]==1){
            jJogadorVez.setText("Jogador 1 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        if(mat[2][0]==1&&mat[1][1]==1&&mat[0][2]==1){
            jJogadorVez.setText("Jogador 1 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        //Jogador 2 Vitorias
        
        //Coluna
        
        if(mat[0][0]==2&&mat[0][1]==2&&mat[0][2]==2){
            jJogadorVez.setText("Jogador 2 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        if(mat[1][0]==2&&mat[1][1]==2&&mat[1][2]==2){
            jJogadorVez.setText("Jogador 2 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        if(mat[2][0]==2&&mat[2][1]==2&&mat[2][2]==2){
            jJogadorVez.setText("Jogador 2 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        //Linha
        
        if(mat[0][0]==2&&mat[1][0]==2&&mat[2][0]==2){
            jJogadorVez.setText("Jogador 2 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        if(mat[0][1]==2&&mat[1][1]==2&&mat[2][1]==2){
            jJogadorVez.setText("Jogador 2 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        if(mat[0][2]==2&&mat[1][2]==2&&mat[2][2]==2){
            jJogadorVez.setText("Jogador 2 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        //Diagonais
        
        if(mat[0][0]==2&&mat[1][1]==2&&mat[2][2]==2){
            jJogadorVez.setText("Jogador 2 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
        
        if(mat[2][0]==2&&mat[1][1]==2&&mat[0][2]==2){
            jJogadorVez.setText("Jogador 2 Venceu, Precione Reiniciar");
            jbotao1.setEnabled(false);
            jbotao2.setEnabled(false);
            jbotao3.setEnabled(false);
            jbotao6.setEnabled(false);
            jbotao5.setEnabled(false);
            jbotao4.setEnabled(false);
            jbotao7.setEnabled(false);
            jbotao8.setEnabled(false);
            jbotao9.setEnabled(false);
        }
                
    }
    
    
}
